{
 "title": "Weather2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "MCP9808 high accuracy dual band gap sensor typical accuracy of ±0.25°C",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "Temp" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windspeed", "legendFormat": "Wind Speed" }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windgust", "legendFormat": "Wind Gust" }
   ]
  },
  {
   "title": "Rain Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rain_hour_rate", "legendFormat": "Temp" }
   ]
  },
  {
   "title": "River Chew",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": " m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "riverlevel", "legendFormat": "Temp" }
   ]
  },
  { "title": "Temperature Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "MCP9808 high accuracy dual band gap sensor typical accuracy of ±0.25°C",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Max temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(temperature[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expr": "avg_over_time(temperature[5m])", "legendFormat": "Temp" }
   ]
  },
  {
   "title": "Avg temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(temperature[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(temperature[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wind Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Wind Direction",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    { "expr": "winddirection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed and Gust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    { "expr": "windspeed", "legendFormat": "Wind Speed" },
    { "expr": "windgust", "legendFormat": "Wind Gust" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "targets": [
    { "expr": "windspeed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "spectraphilic-windrose-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "windspeed", "legendFormat": "speed" },
    { "expr": "winddirection", "legendFormat": "direction" }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "targets": [
    { "expr": "windgust", "legendFormat": "__auto" }
   ]
  },
  { "title": "River", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  { "title": "River", "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 } },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max_over_time(riverlevel[24h])", "legendFormat": "Max" }
   ]
  },
  {
   "title": "River level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    { "expr": "riverlevel", "legendFormat": "River level" }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min_over_time(riverlevel[24h])", "legendFormat": "Max" }
   ]
  }
 ]
}