// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"time"
)

type Weather struct {
	Record        time.Time `json:"record"`
	Temperature   float64   `json:"temperature"`
	Pressure      float64   `json:"pressure"`
	RainMm        float64   `json:"rain_mm"`
	WindSpeed     float64   `json:"wind_speed"`
	WindDirection int32     `json:"wind_direction"`
}
