// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"time"
)

type Weather struct {
	RecordDate    time.Time `json:"record_date"`
	Temperature   float64   `json:"temperature"`
	Pressure      float64   `json:"pressure"`
	RainMm        float64   `json:"rain_mm"`
	WindSpeed     float64   `json:"wind_speed"`
	WindGust      float64   `json:"wind_gust"`
	WindDirection float64   `json:"wind_direction"`
}
