// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"context"
	"time"
)

type Querier interface {
	GetAllRecords(ctx context.Context) ([]Weather, error)
	WriteRecord(ctx context.Context, arg WriteRecordParams) (time.Time, error)
}

var _ Querier = (*Queries)(nil)
